"""add message seq ordering column + history index

Revision ID: b3f1a2c4d5e6
Revises: 0f703575e678
Create Date: 2026-09-24 10:15:00.000000+00:00

Zero-downtime pattern (expand -> backfill -> contract):
1. add `messages.seq` as nullable
2. backfill deterministic order: created_at ASC, user-before-assistant on
   ties, then id
3. set NOT NULL, attach an identity sequence restarted above max(seq)
4. composite index (user_id, agent_id, sub_agent_id, seq) for the history
   query (fix-doc F7)
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b3f1a2c4d5e6"
down_revision = "0f703575e678"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. expand
    op.add_column("messages", sa.Column("seq", sa.BigInteger(), nullable=True))

    # 2. backfill (deterministic even when user+assistant share created_at)
    op.execute(
        """
        WITH ordered AS (
            SELECT id, ROW_NUMBER() OVER (
                ORDER BY created_at ASC, (role = 'user') DESC, id ASC
            ) AS rn
            FROM messages
        )
        UPDATE messages m
        SET seq = o.rn
        FROM ordered o
        WHERE m.id = o.id
        """
    )

    # 3. contract: NOT NULL + identity continuing above the backfilled values
    op.execute("ALTER TABLE messages ALTER COLUMN seq SET NOT NULL")
    op.execute(
        "ALTER TABLE messages ALTER COLUMN seq "
        "ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    max_seq = op.get_bind().execute(
        sa.text("SELECT COALESCE(MAX(seq), 0) FROM messages")
    ).scalar_one()
    op.execute(f"ALTER TABLE messages ALTER COLUMN seq RESTART WITH {max_seq + 1}")
    op.create_index("ix_messages_seq", "messages", ["seq"], unique=True)

    # 4. history query index (covers fix-doc F7)
    op.create_index(
        "ix_messages_history",
        "messages",
        ["user_id", "agent_id", "sub_agent_id", "seq"],
    )


def downgrade() -> None:
    op.drop_index("ix_messages_history", table_name="messages")
    op.drop_index("ix_messages_seq", table_name="messages")
    op.execute(
        "ALTER TABLE messages ALTER COLUMN seq DROP IDENTITY IF EXISTS"
    )
    op.drop_column("messages", "seq")
